"""empty message

Revision ID: 4134c935a85c
Revises: None
Create Date: 2015-12-05 17:04:24.214187

"""

# revision identifiers, used by Alembic.
revision = '4134c935a85c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'questions', sa.Column('author_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'questions', 'author_id')
    op.drop_table('users')
    ### end Alembic commands ###
